{
 "title": "application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "비속어수치",
   "type": "stat",
   "description": "-1 : null/\n0~0.4 : 일반/\n0.4~1 : 욕설",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "chat_time", "id": "2", "settings": { "interval": "10s", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "abuse",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "분당 비속어 개수",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "alias": "비속어",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "abuse:[0.4 TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "긍/부정 수치",
   "type": "stat",
   "description": "-1 : null/\n0~0.4 : 부정/\n0.4~1 : 긍정",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "chat_time", "id": "2", "settings": { "interval": "10s", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "emotion",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "분당 긍/부정 개수",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 5 },
   "targets": [
    {
     "alias": "긍정",
     "bucketAggs": [
      { "field": "chat_time", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "emotion:[0.4 TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "status-history",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 9 },
   "targets": [
    {
     "alias": "부정",
     "bucketAggs": [
      { "field": "chat_time", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "emotion:[* TO 0.4]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "input_data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expression": "$A * 60", "type": "math" }
   ]
  },
  {
   "title": "output_data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "alias": "output_data",
     "bucketAggs": [
      { "field": "chat_time", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}