{
 "title": "kafka/spark",
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "topic_offset",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "inchat_offset",
     "measurement": "burrow_topic",
     "query": "SELECT \"value\" FROM \"burrow_topic\" WHERE (\"topic\" = 'outchat') AND $timeFilter",
     "select": [
      [
       { "params": [ "offset" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "inchat" }
     ]
    },
    {
     "alias": "outchat_offset",
     "measurement": "burrow_topic",
     "query": "SELECT \"value\" FROM \"burrow_topic\" WHERE (\"topic\" = 'outchat') AND $timeFilter",
     "select": [
      [
       { "params": [ "offset" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "outchat" }
     ]
    }
   ]
  },
  {
   "title": "topic_offset",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
   "targets": [
    {
     "alias": "inchat_offset",
     "measurement": "burrow_topic",
     "query": "SELECT \"value\" FROM \"burrow_topic\" WHERE (\"topic\" = 'outchat') AND $timeFilter",
     "select": [
      [
       { "params": [ "offset" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "inchat" }
     ]
    },
    {
     "alias": "outchat_offset",
     "measurement": "burrow_topic",
     "query": "SELECT \"value\" FROM \"burrow_topic\" WHERE (\"topic\" = 'outchat') AND $timeFilter",
     "select": [
      [
       { "params": [ "offset" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "outchat" }
     ]
    }
   ]
  },
  {
   "title": "kafka_lags",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "alias": "kafka_lags",
     "measurement": "burrow_partition",
     "query": "SELECT \"used\" FROM \"swap\" WHERE (\"host\" = 'select tag value') AND $timeFilter",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "토픽별 메시지수",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "inchat",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kafkaFlink",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "outchat" }
     ]
    },
    {
     "alias": "outchat",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kafkaFlink",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "outchat" }
     ]
    }
   ]
  },
  {
   "title": "토픽별 메시지량",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "inchat",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kafkaFlink",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "inchat" }
     ]
    },
    {
     "alias": "outchat",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kafkaFlink",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "outchat" }
     ]
    }
   ]
  },
  { "title": "spark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "총 task",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(app-20210809234149-0000.0.executor.recordsRead.count, 'throughput')"
    }
   ]
  },
  {
   "title": "완료 된 task",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(app-20210809234149-0000.0.executor.*.completeTasks, 'complete task')"
    }
   ]
  },
  {
   "title": "완료/성공 된 task",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 14 },
   "targets": [
    {
     "target": "alias(app-20210809234149-0000.0.executor.*.completeTasks, 'complete task')"
    },
    {
     "target": "alias(app-20210809234149-0000.0.executor.succeededTasks.count, 'succeeded task')"
    },
    {
     "target": "alias(app-20210809234149-0000.0.executor.recordsRead.count, 'throughput')"
    }
   ]
  },
  {
   "title": "task 당 처리시간(초)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/1000", "type": "math" }
   ]
  },
  {
   "title": "Task 실행여부",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "app-20210809234149-0000.0.executor.threadpool.activeTasks"
    }
   ]
  }
 ]
}