version: "3.2"
services:
  spark-master:
    image: merolhack/spark:latest
    container_name: spark-master
    hostname: spark-master
    build:
      context: spark-master/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
      - 18081:18080
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      # - NVIDIA_VISIBLE_DEVICES=0
    command: "/start-master.sh"
    # runtime: "nvidia"
    #  - NVIDIA_VISIBLE_DEVICES=0
    command: "/start-master.sh"
    #runtime: "nvidia"
>>>>>>> 66e0b7a413d87fe3ced73e5e0e660a46887ff5c3

  spark-worker:
    image: merolhack/spark:latest
    depends_on:
      - spark-master
    ports:
      - 8080
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8080
    command: "/start-worker.sh"

  kafka:
    image: kafka:latest
    container_name: kafka
    hostname: kafka
    build:
      context: kafkadocker/
      dockerfile: Dockerfile
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "test123:1:1,inchat:1:1,outchat:1:1"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 100001200
      KAFKA_MESSAGE_MAX_BYTES: 100001200
      KAFKA_CFG_MAX_REQUEST_SIZE: 100001200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONOG_INITDB_DATABASE=mymodel
    volumes:
      - ./data/db:/data/db
    command: mongod --auth

  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node

  logstash:
    container_name: logstash
    hostname: logstash
    build:
      context: logstash/
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: false
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: false
    ports:
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  flask:
    container_name: flask
    restart: always
    build: ./flaskdocker
    expose:
      - 5005
<<<<<<< HEAD
    # environment: 
    #   - NVIDIA_VISIBLE_DEVICES=0
    # runtime: nvidia
=======
    #environment: 
    #  - NVIDIA_VISIBLE_DEVICES=0
    #runtime: nvidia
>>>>>>> 66e0b7a413d87fe3ced73e5e0e660a46887ff5c3

  nginx:
    container_name: nginx
    restart: always
    build: ./nginxdocker
    ports:
      - 5307:5307

  postgresql:
    image: docker.io/bitnami/postgresql:10-debian-10
    volumes:
      - ./postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    volumes:
      - ./redis_data:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2-debian-10
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Asia/Seoul
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Seoul
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
  
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2-debian-10
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Asia/Seoul
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Seoul
    volumes:
      - ./dags:/opt/bitnami/airflow/dags

  airflow:
    image: docker.io/bitnami/airflow:2-debian-10
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Asia/Seoul
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Seoul
    ports:
      - 8083:8080
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:38081/render
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=hyu.javas@gmail.com
      - GF_SMTP_PASSWORD=hyusd2s@0614!2021
      - GF_SMTP_FROM_ADDRESS=hyu.javas@gmail.com


  grafana-image-renderer:
    image: grafana/grafana-image-renderer:3.0.1
    environment:
      - IGNORE_HTTPS_ERRORS=true
    ports:
      - 38081:8081

  influxdb:
    image: influxdb:1.8.6
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=chatbotvi
      - INFLUXDB_USER=adminuser
      - INFLUXDB_USER_PASSWORD=adminuser
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.Hostname}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086 -storage_driver_buffer_duration=5s
    ports:
      - 18080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influxdb
    deploy:
      mode: global

  burrow:
    build: ./burrowdocker
    volumes:
      - ./burrowdocker/docker-config:/etc/burrow/
      - ./burrowdocker/tmp:/var/tmp/burrow
    ports:
      - 7000:7000
    depends_on:
      - kafka
    restart: always

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./telegrafdocker/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "80:80"
      - "2003:2003"
      - "2003:2003/udp"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8087:8080"
      - "8125:8125/udp"
      - "8126:8126"
    environment:
      - MEMCACHE_HOST=127.0.0.1:11211
      - CACHE_DURATION=60
    volumes:
      - ./graphite_data/conf:/opt/graphite/conf
      - ./graphite_data/storage:/opt/graphite/storage
      - ./graphite_data/statsd_config:/opt/statsd/config
      - ./graphite_data/storage/log/webapp:/opt/graphite/storage/log/webapp
      - ./graphite_data/storage/log/supervisor:/var/log/supervisor
    restart: unless-stopped

  jobmanager:
    image: flink:1.13.1-scala_2.11-java8
    ports:
      - "8089:8081"
      - "6123:6123"
    command: standalone-job --job-classname org.example.KafkaToInfluxDB  /opt/flink/usrlib/KafkaToInfluxDB.jar
    volumes:
      - ./flink_lib:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 8089 
        parallelism.default: 2 

  taskmanager:
    image: flink:1.13.1-scala_2.11-java8
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./flink_lib:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 8089
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
