version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    logfile:
        class: logging.handlers.ConcurrentRotatingFileHandler
        level: DEBUG
        formatter: simple
        maxBytes: 10485760 # 10MB
        backupCount: 20
        filename: ./logs/info.log

root:
    level: DEBUG
    handlers: [logfile]